# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Vivado Projects/Lab_05/Lab_05.cache/wt} [current_project]
set_property parent.project_path {D:/Vivado Projects/Lab_05/Lab_05.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/Vivado Projects/Lab_05/Lab_05.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  {D:/Vivado Projects/Lab_02/Lab_02.srcs/sources_1/new/Lab_02_Full_Adder.sv}
  {D:/Vivado Projects/Lab_02/Lab_02.srcs/sources_1/new/Ripple_Carry_Adder.sv}
  {D:/Vivado Projects/Lab_05/Lab_05.srcs/sources_1/new/dff.sv}
  {D:/Vivado Projects/Lab_05/Lab_05.srcs/sources_1/new/eight_seg.sv}
  {D:/Vivado Projects/Lab_03/Lab_03.srcs/sources_1/new/mux2.sv}
  {D:/Vivado Projects/Lab_04/Lab_04.srcs/sources_1/new/v_chk.sv}
  {D:/Vivado Projects/Lab_05/Lab_05.srcs/sources_1/new/Lab_05.sv}
  {D:/Vivado Projects/Lab_04/Lab_04.srcs/sources_1/new/Lab_04.sv}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Vivado Projects/Lab_05/Lab_05.srcs/constrs_1/new/cnst.xdc}}
set_property used_in_implementation false [get_files {{D:/Vivado Projects/Lab_05/Lab_05.srcs/constrs_1/new/cnst.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Lab_05 -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Lab_05.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Lab_05_utilization_synth.rpt -pb Lab_05_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
